### ISSUE TITLE
Work with gzipped files

### ISSUE THREAD

**Issue by rrwick** [scwatts/genome_painter#2]
The `paint_genome` tool currently produces a tsv file. This can be very large, especially if the database has many species, but it's not complex and compresses very well. It'd therefore be nice if `paint_genome` could output tsv.gz files to save space. And then the visualisation/summary tools should accept gzipped input.

**Comment by scwatts** [comment]
This feature has been completed in 9d797d3276a195c52ef4cfab3ff18f2d85ff661d and 2f59d09e0806ca6649ea79e4eea697852ef68e69. Thanks for the suggestion!

**Comment by rrwick** [comment]
Yay!
