### ISSUE TITLE
Command names too generic

### ISSUE THREAD

**Issue by tseemann** [scwatts/genome_painter#3]
Would it be possible to prefix the commands with `genomepainter-xxxxx` or something?
`count-kmers` etc is a bit vague to be in the PATH

**Comment by scwatts** [comment]
Sure thing. I've made a new release which includes more uniquely named executables and updated the instructions for compiling from source to reflect this. Thanks for the suggestion!

**Comment by tseemann** [comment]
I just tried 0.0.7 and `make install` still uses the old names?

```
  /usr/bin/install -c count_kmers generate_database paint_genome '/home/linuxbrew/.linuxbrew/Cellar/genome-painter/0.0.7/bin'

 /usr/bin/install -c scripts/summarise_contigs.py scripts/summarise_species.py scripts/plot_painting.py '/home/linuxbrew/.linuxbrew/Cellar/genome-painter/0.0.7/bin'
```

**Comment by scwatts** [comment]
I hadn't changed the behaviour of the build system, just the instructions to set a prefix for executable names. I've now set autoconf to use `genomepainter_` as the default program prefix so this should work as expected now
